#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : R-etm
Version  : 1.1.2
Release  : 54
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/etm_1.1.2.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/etm_1.1.2.tar.gz
Summary  : Empirical Transition Matrix
Group    : Development/Tools
License  : MIT
Requires: R-etm-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-RcppArmadillo
Requires: R-data.table
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : R-RcppArmadillo-dev
BuildRequires : R-data.table
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# etm
Non-parametric estimation of the matrix of transition probabilities for any time-inhomogeneous multistate model with finite state space.

%package lib
Summary: lib components for the R-etm package.
Group: Libraries

%description lib
lib components for the R-etm package.


%prep
%setup -q -n etm
pushd ..
cp -a etm buildavx2
popd
pushd ..
cp -a etm buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744640831

%install
export SOURCE_DATE_EPOCH=1744640831
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/etm/CITATION
/usr/lib64/R/library/etm/DESCRIPTION
/usr/lib64/R/library/etm/INDEX
/usr/lib64/R/library/etm/LICENSE
/usr/lib64/R/library/etm/Meta/Rd.rds
/usr/lib64/R/library/etm/Meta/data.rds
/usr/lib64/R/library/etm/Meta/features.rds
/usr/lib64/R/library/etm/Meta/hsearch.rds
/usr/lib64/R/library/etm/Meta/links.rds
/usr/lib64/R/library/etm/Meta/nsInfo.rds
/usr/lib64/R/library/etm/Meta/package.rds
/usr/lib64/R/library/etm/Meta/vignette.rds
/usr/lib64/R/library/etm/NAMESPACE
/usr/lib64/R/library/etm/R/etm
/usr/lib64/R/library/etm/R/etm.rdb
/usr/lib64/R/library/etm/R/etm.rdx
/usr/lib64/R/library/etm/data/abortion.txt.gz
/usr/lib64/R/library/etm/data/fourD.rda
/usr/lib64/R/library/etm/data/los.data.csv.gz
/usr/lib64/R/library/etm/data/sir.cont.txt.gz
/usr/lib64/R/library/etm/doc/etmCIF_tutorial.R
/usr/lib64/R/library/etm/doc/etmCIF_tutorial.Rnw
/usr/lib64/R/library/etm/doc/etmCIF_tutorial.pdf
/usr/lib64/R/library/etm/doc/index.html
/usr/lib64/R/library/etm/help/AnIndex
/usr/lib64/R/library/etm/help/aliases.rds
/usr/lib64/R/library/etm/help/etm.rdb
/usr/lib64/R/library/etm/help/etm.rdx
/usr/lib64/R/library/etm/help/paths.rds
/usr/lib64/R/library/etm/html/00Index.html
/usr/lib64/R/library/etm/html/R.css
/usr/lib64/R/library/etm/tests/test.etmCIF.R
/usr/lib64/R/library/etm/tests/test.etmCIF.Rout.save
/usr/lib64/R/library/etm/tests/tests.etm.R
/usr/lib64/R/library/etm/tests/tests.etm.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/etm/libs/etm.so
/V4/usr/lib64/R/library/etm/libs/etm.so
/usr/lib64/R/library/etm/libs/etm.so
